import { CommercialVehicle } from './types';

export const ALL_COMMERCIAL_VEHICLES: CommercialVehicle[] = [
  // ================= TRUCKS (LCV, ICV, TIPPERS, CNG) =================
  {
    id: 'sartaj-gs-5252',
    name: 'Sartaj GS 5252',
    series: 'Sartaj Global Series',
    tagline: 'Best-in-class mileage for last-mile logistics & intra-city cargo',
    category: 'trucks',
    subCategory: 'lcv',
    subCategoryLabel: 'Light Commercial Vehicle (4-Tyre)',
    startingPrice: '₹ 14.65 Lakh*',
    gvw: '5,200 kg',
    power: '102 HP @ 2600 rpm',
    seatingOrPayload: 'Payload: ~2.8 Tonnes',
    fuelType: 'Diesel',
    applications: ['FMCG Distribution', 'Parcel & E-commerce Logistics', 'Beverage Crates', 'White Goods Transport', 'Fruit & Vegetable Delivery'],
    image: '/assets/raozmotors/truck_sartaj_5252.jpg',
    highlights: [
      'Proven 4-Cylinder Common Rail Turbo Engine',
      'Class-leading fuel economy with Eco Drive Mode',
      'Driver-comfort cabin with power steering & reclining seats',
      'Heavy-duty chassis with ladder-type frame'
    ],
    specs: {
      engine: 'SLT6 In-line 4 Cylinder BS6 Phase 2 CRDi Turbocharged Intercooled',
      maxPower: '102 HP (75 kW) @ 2600 rpm',
      maxTorque: '315 Nm @ 1400 - 1600 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 OBD-2 Compliant',
      transmission: 'Synchromesh 5-Speed Manual (5 Forward + 1 Reverse)',
      clutch: 'Single Dry Plate Diaphragm Type 280 mm dia',
      gvw: '5,200 kg',
      payload: '2,810 kg',
      wheelbase: '2,815 mm / 3,335 mm',
      overallLength: '5,310 mm',
      cargoDeckLength: '10.2 ft / 12.3 ft',
      fuelTank: '90 Litres Diesel',
      fuelType: 'Diesel',
      brakes: 'Hydraulic Vacuum Assisted Dual Circuit Brakes',
      steering: 'Hydraulic Power Steering (Tilt & Telescopic)',
      suspension: 'Semi-Elliptical Multi-Leaf Springs with Hydraulic Shock Absorbers',
      tyres: '7.50 R 16 - 16 PR (Rib / Lug)',
      gradeability: '28%',
      topSpeed: '85 km/h (Electronically Governed)'
    },
    overview: 'The Sartaj GS 5252 is engineered for transporters who demand exceptional fuel economy, robust load carrying reliability, and effortless city maneuverability. Its ergonomic cabin and low loading deck height make rapid dock-to-store deliveries seamless.'
  },
  {
    id: 'sartaj-hg-72',
    name: 'Sartaj HG 72',
    series: 'Sartaj Heavy Duty Series',
    tagline: 'High payload 6-wheeler workhorse for regional distribution',
    category: 'trucks',
    subCategory: 'lcv',
    subCategoryLabel: 'Light Commercial Vehicle (6-Tyre)',
    startingPrice: '₹ 16.20 Lakh*',
    gvw: '7,200 kg',
    power: '102 HP @ 2600 rpm',
    seatingOrPayload: 'Payload: ~4.4 Tonnes',
    fuelType: 'Diesel',
    applications: ['Agri Produce & Grain Bags', 'Textile Bales', 'Hardware & Plywood', 'Cement Retail', 'LPG Cylinder Distribution'],
    image: '/assets/raozmotors/truck_prestige_delivery.jpg',
    highlights: [
      'Robust 6-wheel platform with heavy-duty rear banjo axle',
      'Dual fuel filter with water separator for long injector life',
      'Wide cargo deck options up to 14.2 ft',
      'Low total cost of ownership (TCO) with 40,000 km oil drain interval'
    ],
    specs: {
      engine: 'SLT6 In-line 4 Cylinder BS6 CRDi Diesel with DPF & SCR',
      maxPower: '102 HP @ 2600 rpm',
      maxTorque: '315 Nm @ 1400 - 1800 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 Phase 2 Compliant',
      transmission: '5-Speed Synchromesh Manual',
      clutch: '280 mm Single Plate Dry Diaphragm',
      gvw: '7,200 kg',
      payload: '4,380 kg',
      wheelbase: '3,335 mm / 3,940 mm',
      cargoDeckLength: '12.3 ft / 14.2 ft',
      fuelTank: '90 Litres with anti-theft locking cap',
      fuelType: 'Diesel',
      brakes: 'Hydraulic Dual Circuit Vacuum Assisted with ABS',
      steering: 'Integral Power Steering',
      suspension: 'Heavy-Duty Semi-Elliptical Leaf Springs front & rear',
      tyres: '8.25 R 16 - 16 PR Heavy Duty',
      gradeability: '25%',
      topSpeed: '80 km/h'
    },
    overview: 'The Sartaj HG 72 bridges the gap between light delivery and heavy haulage. With 7.2 tonnes GVW and 6 heavy-duty wheels, it easily tackles uneven regional routes and heavy cargo without compromising on fuel economy.'
  },
  {
    id: 'sartaj-59-cng',
    name: 'Sartaj 59 CNG',
    series: 'Eco-Green Clean Mobility',
    tagline: 'Zero-diesel compliance for metro green corridors & clean air zones',
    category: 'trucks',
    subCategory: 'cng',
    subCategoryLabel: 'CNG Green Commercial Vehicle',
    startingPrice: '₹ 15.80 Lakh*',
    gvw: '5,990 kg',
    power: '95 HP @ 2600 rpm',
    seatingOrPayload: 'Payload: ~3.1 Tonnes',
    fuelType: 'CNG',
    applications: ['Metro City Intra-Logistics', 'Municipal Green Garbage', 'Dairy & Bakery Delivery', 'E-commerce Urban Vans'],
    image: '/assets/raozmotors/truck_cng_eco.jpg',
    highlights: [
      'Multi-point sequential CNG injection with dual spark plugs',
      'Cascade cylinder layout providing 240L / 300L CNG capacity',
      'No DEF (AdBlue) required – drastically lowered running cost',
      'Exempted from metro diesel entry bans & clean fuel incentives'
    ],
    specs: {
      engine: 'SLT6 Gas 4-Cylinder Turbocharged CNG Engine with Intercooler',
      maxPower: '95 HP (70 kW) @ 2600 rpm',
      maxTorque: '285 Nm @ 1400 - 1800 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 Phase 2 Clean Fuel',
      transmission: '5-Speed Synchromesh Manual',
      clutch: '280 mm Dry Diaphragm',
      gvw: '5,990 kg',
      payload: '3,120 kg',
      wheelbase: '3,335 mm',
      cargoDeckLength: '12.3 ft',
      fuelTank: '3x 80L Cascaded High-Tensile Steel CNG Cylinders (240L)',
      fuelType: 'CNG',
      brakes: 'Hydraulic Vacuum Assisted Dual Circuit with ABS',
      steering: 'Hydraulic Power Steering',
      suspension: 'Semi-Elliptical Leaf Springs with Telescopic Dampers',
      tyres: '7.50 R 16 - 16 PR',
      gradeability: '22%',
      topSpeed: '80 km/h'
    },
    overview: 'Built specifically for metropolitan logistics where emission restrictions are strict, the Sartaj 59 CNG guarantees unrestricted entry into low-emission zones while cutting fuel expenditure by up to 35% compared to diesel.'
  },
  {
    id: 'samrat-gs',
    name: 'Samrat GS',
    series: 'Samrat Intermediate Commercial Vehicle',
    tagline: 'The undisputed champion of 10.7-tonne intermediate haulage',
    category: 'trucks',
    subCategory: 'icv',
    subCategoryLabel: 'Intermediate Commercial Vehicle (6-Tyre)',
    startingPrice: '₹ 18.90 Lakh*',
    gvw: '10,700 kg',
    power: '115 HP @ 2400 rpm',
    seatingOrPayload: 'Payload: ~6.8 Tonnes',
    fuelType: 'Diesel',
    applications: ['Intercity Cargo Express', 'Textiles & Yarn', 'Industrial Machinery Parts', 'Agri Produce Wholesale', 'Steel Tubes & Rods'],
    image: '/assets/raozmotors/truck_samrat_gs.jpg',
    highlights: [
      'High-torque SLT6 115 HP Turbo Diesel with electronic common rail',
      'Full Air S-Cam Dual Circuit Brakes with ABS for fail-safe stopping',
      'Extra-wide 2.2m cabin with sleeper berth provision',
      'Heavy-duty forged I-beam front axle and full-floating rear axle'
    ],
    specs: {
      engine: 'SLT6 4-Cylinder In-line BS6 CRDi Turbocharged Intercooled with DOC+DPF+SCR',
      maxPower: '115 HP (85 kW) @ 2400 rpm',
      maxTorque: '400 Nm @ 1300 - 1700 rpm',
      displacement: '3455 cc High Output',
      emissionNorms: 'BS6 Phase 2 OBD-2',
      transmission: '6-Speed Overdrive Manual Synchromesh',
      clutch: '310 mm Heavy Duty Single Dry Plate',
      gvw: '10,700 kg',
      payload: '6,850 kg',
      wheelbase: '3,940 mm / 4,760 mm',
      cargoDeckLength: '17.2 ft / 21.6 ft',
      fuelTank: '180 Litres Heavy Duty Aluminium Tank',
      fuelType: 'Diesel',
      brakes: 'Full Air Dual Circuit S-Cam Brakes with Auto Slack Adjuster & ABS',
      steering: 'Tilt & Telescopic Integral Power Steering',
      suspension: 'Semi-Elliptical Multi-Leaf Springs with Anti-Roll Bar front & rear',
      tyres: '8.25 R 20 - 16 PR Radial',
      gradeability: '26%',
      topSpeed: '80 km/h'
    },
    overview: 'The Samrat GS is the backbone of Indian inter-city freight transport. Known for its unmatched chassis toughness and responsive 400 Nm low-end torque, it handles full payloads across mountain climbs and highway stretches with effortless ease.'
  },
  {
    id: 'samrat-gs-xt',
    name: 'Samrat GS XT',
    series: 'Samrat Extra Tough Series',
    tagline: 'High volume extended cargo platform for e-commerce and lightweight goods',
    category: 'trucks',
    subCategory: 'icv',
    subCategoryLabel: 'ICV Long Cargo Platform (6-Tyre)',
    startingPrice: '₹ 19.85 Lakh*',
    gvw: '11,120 kg',
    power: '115 HP @ 2400 rpm',
    seatingOrPayload: 'Payload: ~7.1 Tonnes',
    fuelType: 'Diesel',
    applications: ['E-commerce Hub-to-Hub', 'Automotive Components', 'Consumer Appliances', 'Courier & Postal Logistics', 'Mattress & Foam Transport'],
    image: '/assets/raozmotors/truck_prestige_delivery.jpg',
    highlights: [
      'Extended 5,100 mm wheelbase supporting deck length up to 24 ft',
      'Reinforced chassis side members with bolted cross braces',
      'Electronic driver info cluster with real-time fuel coaching',
      'Factory-fitted SML Saarthi telematics GPS device'
    ],
    specs: {
      engine: 'SLT6 High Output BS6 Phase 2 Diesel',
      maxPower: '115 HP @ 2400 rpm',
      maxTorque: '400 Nm @ 1300 - 1700 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 OBD-2 Compliant',
      transmission: '6-Speed Synchromesh Manual',
      clutch: '310 mm Dry Diaphragm',
      gvw: '11,120 kg',
      payload: '7,150 kg',
      wheelbase: '4,760 mm / 5,100 mm',
      cargoDeckLength: '22 ft / 24 ft High-Cube Container Compatible',
      fuelTank: '180 Litres Aluminium Tank with fuel anti-siphon',
      fuelType: 'Diesel',
      brakes: 'Full Air Dual Circuit with ABS',
      steering: 'Hydraulic Power Steering with adjustable column',
      suspension: 'Parabolic Leaf Springs in front, Semi-Elliptical in rear',
      tyres: '8.25 R 20 - 16 PR',
      gradeability: '24%',
      topSpeed: '80 km/h'
    },
    overview: 'With the exponential boom in express courier and e-commerce distribution, the Samrat GS XT delivers massive cubic capacity with up to 24 feet cargo beds, allowing transporters to pack high-volume, low-density cargo without exceeding GVW limits.'
  },
  {
    id: 'supreme-gs',
    name: 'Supreme GS',
    series: 'Supreme Heavy ICV Series',
    tagline: 'Maximum 11,990 kg GVW heavy intermediate truck with highest load capacity',
    category: 'trucks',
    subCategory: 'icv',
    subCategoryLabel: 'Heavy ICV Commercial Truck',
    startingPrice: '₹ 21.30 Lakh*',
    gvw: '11,990 kg',
    power: '120 HP @ 2400 rpm',
    seatingOrPayload: 'Payload: ~7.9 Tonnes',
    fuelType: 'Diesel',
    applications: ['Heavy Machinery Transport', 'Steel Coils & Sheets', 'Bulk Food Grains', 'Timber & Heavy Building Materials', 'Beverage Distribution'],
    image: '/assets/raozmotors/truck_supreme_heavy.jpg',
    highlights: [
      'Top-of-the-line 11,990 kg GVW – maximum in the intermediate class',
      'Enhanced 120 HP engine calibration for steep hill traction',
      'Heavy-duty 7-tonne rear hypoid axle for maximum overload reserve',
      'Factory warranty of 3 Years / Unlimited Kilometres'
    ],
    specs: {
      engine: 'SLT6 High-Performance 4-Cylinder CRDi Diesel',
      maxPower: '120 HP (88 kW) @ 2400 rpm',
      maxTorque: '420 Nm @ 1250 - 1650 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 Phase 2',
      transmission: '6-Speed Synchromesh with Overdrive',
      clutch: '330 mm Heavy-Duty Clutch Plate',
      gvw: '11,990 kg',
      payload: '7,890 kg',
      wheelbase: '4,270 mm / 4,760 mm',
      cargoDeckLength: '19.2 ft / 22.5 ft',
      fuelTank: '200 Litres Heavy Duty Aluminium',
      fuelType: 'Diesel',
      brakes: 'Full Air S-Cam with ABS & Automatic Slack Adjuster',
      steering: 'Recirculating Ball Power Steering',
      suspension: 'Multi-Leaf Heavy Spring with Heavy Shock Absorbers',
      tyres: '9.00 R 20 - 16 PR All-Steel Radials',
      gradeability: '27%',
      topSpeed: '80 km/h'
    },
    overview: 'The Supreme GS represents the ultimate evolution in intermediate commercial vehicles. Specially reinforced for rigorous long-haul duty cycles, it delivers the highest payload in its category while keeping fuel consumption strictly economical.'
  },
  {
    id: 'samrat-gs-tipper',
    name: 'Samrat GS Tipper',
    series: 'Construction & Mining Series',
    tagline: 'Rugged tipper with high-strength hydraulic hoist for construction materials',
    category: 'trucks',
    subCategory: 'tipper',
    subCategoryLabel: 'Heavy Tipper / Dumper',
    startingPrice: '₹ 20.40 Lakh*',
    gvw: '10,700 kg',
    power: '115 HP @ 2400 rpm',
    seatingOrPayload: 'Box Body: 4.5 & 6.5 Cu.M',
    fuelType: 'Diesel',
    applications: ['Sand & Gravel Transport', 'Stone Crusher & Aggregates', 'Road Construction & Asphalt', 'Earth Excavation', 'Fly Ash & Clinker'],
    image: '/assets/raozmotors/truck_tipper_construction.jpg',
    highlights: [
      'Heavy-duty hydraulic cylinder hoist with fast tipping cycle (<18 sec)',
      'High-tensile wear-resistant Hardox steel body (4.5 & 6.5 Cu.M)',
      'Reinforced leaf springs with double helper springs for quarry roads',
      'High ground clearance with underbody rock guard protection'
    ],
    specs: {
      engine: 'SLT6 Turbo Diesel BS6 with SCR & DPF',
      maxPower: '115 HP @ 2400 rpm',
      maxTorque: '400 Nm @ 1300 - 1700 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 Phase 2',
      transmission: '5-Speed Heavy Duty Manual with PTO (Power Take-Off)',
      clutch: '310 mm Heavy Duty Ceramic Faced',
      gvw: '10,700 kg',
      payload: 'Body Volume: 4.5 Cu.M / 6.5 Cu.M Rock Body',
      wheelbase: '2,815 mm Compact Turning Radius',
      fuelTank: '90 Litres Diesel Tank with Steel Guard',
      fuelType: 'Diesel',
      brakes: 'Full Air Dual Circuit with ABS',
      steering: 'Hydraulic Power Steering with Heavy Knuckle',
      suspension: 'Semi-Elliptical Heavy-Duty Springs with 14 Leaves + 8 Helper Leaves',
      tyres: '8.25 R 20 - 16 PR Mining Lug Pattern',
      gradeability: '34%',
      topSpeed: '75 km/h'
    },
    overview: 'Engineered specifically for demanding quarry, road construction, and earthmoving works, the Samrat GS Tipper combines rapid tipping cycle times with an ultra-short 2,815 mm turning radius to maneuver effortlessly in tight project sites.'
  },

  // ================= BUSES (SCHOOL, STAFF, LUXURY, TOURIST) =================
  {
    id: 'sml-saathi-school-bus',
    name: 'SML Saathi School Bus',
    series: 'SafeKids Bus Series',
    tagline: 'India’s most trusted school bus with AIS 052 & AIS 063 safety compliance',
    category: 'buses',
    subCategory: 'school_bus',
    subCategoryLabel: 'School & College Bus',
    startingPrice: '₹ 17.50 Lakh*',
    gvw: '5,990 kg',
    power: '102 HP @ 2600 rpm',
    seatingOrPayload: 'Seating: 24 to 34 Children',
    fuelType: 'Diesel',
    applications: ['K-12 School Transport', 'Pre-schools & Day Care', 'College & University Campus Commute', 'Sports Academy Shuttle'],
    image: '/assets/raozmotors/bus_school_saathi.jpg',
    highlights: [
      'Strict AIS 052 (Bus Code) & AIS 063 (School Bus Safety) Certified',
      'Child-safe low entry first step with auxiliary fold-out safety step',
      'Anti-skid vinyl flooring, padded grab rails & chin-guard seats',
      'Speed governor factory set to 40 km/h with GPS SOS emergency buzzer'
    ],
    specs: {
      engine: 'SLT6 In-line 4-Cylinder BS6 Turbo Diesel with SCR',
      maxPower: '102 HP @ 2600 rpm',
      maxTorque: '315 Nm @ 1400 - 1600 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 OBD-2 Compliant',
      transmission: '5-Speed Manual Synchromesh',
      clutch: '280 mm Single Plate Dry Diaphragm',
      gvw: '5,990 kg',
      seatingCapacity: '24+D / 30+D / 34+D (Child Seating 3x2 Configuration)',
      wheelbase: '3,335 mm',
      overallLength: '6,200 mm',
      fuelTank: '90 Litres Diesel',
      fuelType: 'Diesel',
      brakes: 'Hydraulic Dual Circuit Vacuum Assisted with ABS',
      steering: 'Hydraulic Power Steering with Ergonomic Steering Wheel',
      suspension: 'Parabolic Soft Suspension for smoother ride on city roads',
      tyres: '7.50 R 16 - 16 PR Radial',
      gradeability: '25%',
      topSpeed: '40 km/h (Factory Governed for Child Safety)'
    },
    overview: 'Trusted by over 4,500 schools across India, the SML Saathi is engineered from the ground up for maximum child safety. Every detail — from rounded corner seat frames and under-seat bag racks to emergency exit doors and CCTV prep — is designed to keep students secure.'
  },
  {
    id: 'executive-school-coach-4240',
    name: 'Executive School Coach 4240',
    series: 'High-Capacity School Series',
    tagline: 'Spacious 48-62 seater campus cruiser for large educational institutions',
    category: 'buses',
    subCategory: 'school_bus',
    subCategoryLabel: 'High Capacity School Coach',
    startingPrice: '₹ 22.80 Lakh*',
    gvw: '8,990 kg',
    power: '115 HP @ 2400 rpm',
    seatingOrPayload: 'Seating: 48 to 62 Children',
    fuelType: 'Diesel',
    applications: ['Large Public & Private Schools', 'Universities & Engineering Colleges', 'Educational Foundations', 'District School Districts'],
    image: '/assets/raozmotors/bus_school_yellow.jpg',
    highlights: [
      'High-capacity 3x3 seating layout for up to 62 students',
      'Dual emergency exits with exterior warning alarms',
      'Full Air Brakes with ABS for reliable stopping even in monsoons',
      'Panoramic safety-glass windows with horizontal safety guard bars'
    ],
    specs: {
      engine: 'SLT6 High-Torque 115 HP BS6 Phase 2 CRDi Diesel',
      maxPower: '115 HP @ 2400 rpm',
      maxTorque: '400 Nm @ 1300 - 1700 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 Phase 2',
      transmission: '5-Speed Synchromesh Manual',
      clutch: '310 mm Dry Diaphragm',
      gvw: '8,990 kg',
      seatingCapacity: '48+D / 54+D / 62+D',
      wheelbase: '4,240 mm',
      overallLength: '8,400 mm',
      fuelTank: '120 Litres Diesel Tank',
      fuelType: 'Diesel',
      brakes: 'Full Air Dual Circuit S-Cam Brakes with ABS',
      steering: 'Tilt and Telescopic Power Steering',
      suspension: 'Semi-Elliptical Multi-Leaf with Anti-Roll Stabilizer',
      tyres: '8.25 R 16 - 16 PR',
      gradeability: '23%',
      topSpeed: '40 km/h (Govt. Governed)'
    },
    overview: 'For large educational institutions transporting thousands of pupils daily, the Executive School Coach 4240 cuts fleet costs in half by consolidating transport into fewer trips while providing exceptional student comfort and emergency preparedness.'
  },
  {
    id: 'executive-lx-staff-coach',
    name: 'Executive LX Staff Coach',
    series: 'Executive Transit Series',
    tagline: 'Premium air-conditioned corporate transit with plush push-back reclining seats',
    category: 'buses',
    subCategory: 'staff_bus',
    subCategoryLabel: 'Corporate Staff & Executive Coach',
    startingPrice: '₹ 24.50 Lakh*',
    gvw: '7,500 kg',
    power: '115 HP @ 2400 rpm',
    seatingOrPayload: 'Seating: 28 to 36 Executives',
    fuelType: 'Diesel',
    applications: ['IT & Tech Park Employee Transit', 'MNC & BPO Commuter Fleet', 'Factory Shift Transportation', 'Airline Crew Shuttle'],
    image: '/assets/raozmotors/bus_executive_staff.jpg',
    highlights: [
      'High-capacity roof-mounted AC with individual louvers & reading lamps',
      'Plush 2x2 pushback reclining seats with calf support & cup holders',
      'USB fast-charging ports at every row & LED ambient roof lighting',
      'Whisper-quiet cabin insulation for productive transit'
    ],
    specs: {
      engine: 'SLT6 Common Rail Turbocharged BS6 Diesel',
      maxPower: '115 HP @ 2400 rpm',
      maxTorque: '400 Nm @ 1300 - 1700 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 OBD-2 Compliant',
      transmission: '5-Speed Manual Synchromesh',
      clutch: '310 mm Heavy Duty Clutch',
      gvw: '7,500 kg',
      seatingCapacity: '28+D / 32+D / 36+D (2x2 Reclining Luxury)',
      wheelbase: '3,940 mm / 4,240 mm',
      overallLength: '8,250 mm',
      fuelTank: '120 Litres Diesel',
      fuelType: 'Diesel',
      brakes: 'Full Air Dual Circuit with ABS',
      steering: 'Hydraulic Integral Power Steering',
      suspension: 'Weveller Air Suspension / Parabolic Springs for cloud-smooth ride',
      tyres: '8.25 R 16 - 16 PR',
      gradeability: '25%',
      topSpeed: '85 km/h'
    },
    overview: 'The Executive LX transforms the daily commute into productive leisure. Specifically created for multinational corporate fleets and IT corridors, it pairs acoustic cabin dampening with individual air vents and plush reclining upholstery.'
  },
  {
    id: 'hiroi-luxury-coach',
    name: 'Hiroi Luxury AC Coach',
    series: 'Hiroi Japanese Precision Luxury',
    tagline: 'Flagship intercity tourist coach with air-suspension and panoramic views',
    category: 'buses',
    subCategory: 'luxury_coach',
    subCategoryLabel: 'Luxury Intercity Tourist Coach',
    startingPrice: '₹ 29.80 Lakh*',
    gvw: '8,990 kg',
    power: '120 HP @ 2400 rpm',
    seatingOrPayload: 'Seating: 28 to 34 Tourist Class',
    fuelType: 'Diesel',
    applications: ['Premium Intercity Tourism & Tours', '5-Star Hotel Guest Transfers', 'Destination Wedding Luxury Guest Transit', 'Pilgrimage VIP Charters'],
    image: '/assets/raozmotors/bus_hiroi_luxury.jpg',
    highlights: [
      'Full Electronically Controlled Air Suspension (ECAS) for serene highway float',
      'Grand panoramic UV-tinted tour windows with blackout pleated curtains',
      'Spacious under-floor luggage hold with 4.5 cubic meter volume',
      'Multi-zone climate control with HEPA allergen air filtration'
    ],
    specs: {
      engine: 'SLT6 High-Performance Turbocharged Diesel Engine',
      maxPower: '120 HP (88 kW) @ 2400 rpm',
      maxTorque: '420 Nm @ 1250 - 1650 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 Phase 2',
      transmission: '6-Speed Manual Overdrive Synchromesh',
      clutch: '330 mm Hydraulic Assisted Ceramic',
      gvw: '8,990 kg',
      seatingCapacity: '28+D / 34+D Harita Luxury Pushback with Footrests',
      wheelbase: '4,240 mm',
      overallLength: '8,650 mm',
      fuelTank: '150 Litres Long-Haul Tank',
      fuelType: 'Diesel',
      brakes: 'Full Air S-Cam with ABS & Automatic Slack Adjusters',
      steering: 'Tilt and Telescopic Power Steering with Leather-wrapped Wheel',
      suspension: 'Full Pneumatic Bellow Air Suspension front and rear',
      tyres: '8.25 R 20 Radials',
      gradeability: '26%',
      topSpeed: '90 km/h'
    },
    overview: 'The Hiroi Luxury Coach is the pinnacle of comfortable passenger travel. Incorporating Japanese chassis dynamics with bespoke Harita push-back seating, it delivers vibration-free intercity touring for discerning passengers and luxury hotels.'
  },
  {
    id: 'super-ab-4240-tourer',
    name: 'Super AB 4240 Tourer',
    series: 'Super Bus Long-Haul Series',
    tagline: 'High-durability all-weather tourer for state transport & tour operators',
    category: 'buses',
    subCategory: 'luxury_coach',
    subCategoryLabel: 'All-Terrain Tourer & Commuter',
    startingPrice: '₹ 21.90 Lakh*',
    gvw: '8,990 kg',
    power: '115 HP @ 2400 rpm',
    seatingOrPayload: 'Seating: 36 to 45 Passengers',
    fuelType: 'Diesel',
    applications: ['Intercity Route Operators', 'Hill Station Tourist Circuits', 'State Transport Stage Carriages', 'Pilgrim Circuit Tours'],
    image: '/assets/raozmotors/bus_tourist_coach.jpg',
    highlights: [
      'High ground clearance (230 mm) for rough rural and mountain roads',
      'Robust galvanised steel tubular frame preventing rust for 10+ years',
      'Spacious overhead luggage racks with LED night aisle lighting',
      'Wide front windshield providing 180-degree scenic vistas'
    ],
    specs: {
      engine: 'SLT6 Turbo Diesel BS6 Phase 2',
      maxPower: '115 HP @ 2400 rpm',
      maxTorque: '400 Nm @ 1300 - 1700 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 OBD-2 Compliant',
      transmission: '5-Speed Manual Synchromesh',
      clutch: '310 mm Dry Diaphragm',
      gvw: '8,990 kg',
      seatingCapacity: '36+D / 40+D / 45+D High Back Comfort Seats',
      wheelbase: '4,240 mm',
      overallLength: '8,400 mm',
      fuelTank: '120 Litres Diesel',
      fuelType: 'Diesel',
      brakes: 'Full Air Dual Circuit with ABS',
      steering: 'Hydraulic Power Steering',
      suspension: 'Semi-Elliptical Multi-Leaf Springs with Heavy Dampers',
      tyres: '8.25 R 16 - 16 PR',
      gradeability: '28%',
      topSpeed: '80 km/h'
    },
    overview: 'Built for relentless day-in day-out operation across diverse terrains, the Super AB 4240 Tourer is celebrated for its low maintenance upkeep, steep hill gradeability, and bulletproof mechanical resilience.'
  },

  // ================= SPECIAL APPLICATION VEHICLES =================
  {
    id: 'lifeline-acls-ambulance',
    name: 'LifeLine ACLS Ambulance',
    series: 'Life Support Medical Series',
    tagline: 'Advanced Cardiac Life Support Mobile ICU with AIS 125 National Ambulance Code compliance',
    category: 'special',
    subCategory: 'ambulance',
    subCategoryLabel: 'Mobile ICU / ACLS Ambulance',
    startingPrice: '₹ 19.50 Lakh*',
    gvw: '5,200 kg',
    power: '102 HP @ 2600 rpm',
    seatingOrPayload: 'Patient ICU + 4 Paramedics',
    fuelType: 'Diesel',
    applications: ['Emergency 108 Ambulance Fleets', 'Multi-Specialty Hospital Emergency Units', 'Trauma & Cardiac Care Mobile Clinics', 'Disaster Relief Centers'],
    image: '/assets/raozmotors/special_ambulance_acls.jpg',
    highlights: [
      'Certified AIS 125 Type D (Advanced Life Support Mobile ICU)',
      'High-roof walk-through saloon with 1.85m interior standing height',
      'Dual pipeline medical oxygen manifold (2x D-Type 47L cylinders)',
      'Auto-loading roll-in multi-level stretcher with shock-absorbing ramp'
    ],
    specs: {
      engine: 'SLT6 Common Rail Turbo Diesel BS6 Phase 2',
      maxPower: '102 HP @ 2600 rpm',
      maxTorque: '315 Nm @ 1400 - 1600 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 Phase 2 Compliant',
      transmission: '5-Speed Manual Synchromesh',
      clutch: '280 mm Single Plate Dry Diaphragm',
      gvw: '5,200 kg',
      seatingCapacity: '1 Patient Stretcher + 1 Spine Board + 4 Paramedic Swivel Chairs',
      wheelbase: '3,335 mm',
      overallLength: '5,600 mm',
      fuelTank: '90 Litres Diesel',
      fuelType: 'Diesel',
      brakes: 'Hydraulic Vacuum Assisted with ABS',
      steering: 'Hydraulic Power Steering',
      suspension: 'Soft-tuned Leaf Springs with auxiliary gas dampers for gentle patient ride',
      tyres: '7.50 R 16 - 16 PR',
      gradeability: '25%',
      topSpeed: '85 km/h'
    },
    overview: 'In critical golden-hour medical emergencies, the LifeLine ACLS Ambulance functions as an intensive care unit on wheels. It integrates medical gas pipelines, dual high-output inverters (220V AC for ventilators/defibrillators), antibacterial washable fiberglass interior walls, and multi-tone sirens with high-intensity 360-degree LED beacon flashers.'
  },
  {
    id: 'cleancity-water-tanker',
    name: 'CleanCity Water Tanker / Sprinkler',
    series: 'Municipal Civic Series',
    tagline: 'High-capacity 5,000L water carrier with high-pressure road-wash jet nozzles',
    category: 'special',
    subCategory: 'municipal',
    subCategoryLabel: 'Civic Utility & Road Sprinkler',
    startingPrice: '₹ 19.80 Lakh*',
    gvw: '10,700 kg',
    power: '115 HP @ 2400 rpm',
    seatingOrPayload: 'Tank Volume: 5,000 to 6,000 Litres',
    fuelType: 'Diesel',
    applications: ['Municipal Road Washing & Anti-Smog Sprinkling', 'Potable Drinking Water Emergency Supply', 'Construction Site Dust Suppression', 'Horticulture & Public Park Watering'],
    image: '/assets/raozmotors/special_water_tanker.jpg',
    highlights: [
      '5,000 Litres elliptical MS tank with food-grade epoxy internal coating',
      'PTO-driven heavy self-priming centrifugal pump (1000 LPM capacity)',
      'Front road-washing duckbill spray nozzles & rear gravity sprinkler bar',
      'Hose reel with 30m high-pressure water cannon monitor for tree washing'
    ],
    specs: {
      engine: 'SLT6 Turbo Diesel BS6 Phase 2',
      maxPower: '115 HP @ 2400 rpm',
      maxTorque: '400 Nm @ 1300 - 1700 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 Phase 2',
      transmission: '5-Speed Manual with Mechanical PTO',
      clutch: '310 mm Heavy Duty',
      gvw: '10,700 kg',
      payload: 'Tank Capacity: 5,000 Litres / 6,000 Litres',
      wheelbase: '3,335 mm / 3,940 mm',
      fuelTank: '90 Litres Diesel',
      fuelType: 'Diesel',
      brakes: 'Full Air Dual Circuit with ABS',
      steering: 'Hydraulic Power Steering',
      suspension: 'Semi-Elliptical Multi-Leaf Springs with Heavy Shocks',
      tyres: '8.25 R 20 - 16 PR',
      gradeability: '25%',
      topSpeed: '75 km/h'
    },
    overview: 'Adopted by municipal corporations and smart city authorities across India, the CleanCity Water Tanker provides indispensable civic service: fighting urban dust pollution through high-pressure mist spraying while providing clean water distribution during summer shortages.'
  },
  {
    id: 'dpr8-garbage-dumper-placer',
    name: 'Dpr-8 Garbage Dumper Placer',
    series: 'Swachh Bharat Waste Management',
    tagline: 'Hydraulic twin-arm skip loader for standard 3.5 – 4.5 cubic meter bins',
    category: 'special',
    subCategory: 'municipal',
    subCategoryLabel: 'Solid Waste Management Vehicle',
    startingPrice: '₹ 18.90 Lakh*',
    gvw: '10,700 kg',
    power: '115 HP @ 2400 rpm',
    seatingOrPayload: 'Bin Capacity: 3.5 – 4.5 Cu.M',
    fuelType: 'Diesel',
    applications: ['Municipal Solid Waste Lifting & Transport', 'Industrial Scrap & Slag Collection', 'Hospital Biomedical Waste Logistics', 'Housing Society Community Waste Clearance'],
    image: '/assets/raozmotors/special_garbage_tipper.jpg',
    highlights: [
      'Twin hydraulic lifting arms with forged lifting hooks & safety latches',
      'Rear hydraulic stabilizer outriggers preventing vehicle tipping during loading',
      'Bin loading and unloading cycle accomplished in under 60 seconds',
      'Tipping angle up to 85 degrees for complete bin discharge without manual intervention'
    ],
    specs: {
      engine: 'SLT6 BS6 CRDi 4-Cylinder Turbo Diesel',
      maxPower: '115 HP @ 2400 rpm',
      maxTorque: '400 Nm @ 1300 - 1700 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 Phase 2',
      transmission: '5-Speed Synchromesh with PTO Drive',
      clutch: '310 mm Heavy Duty Single Dry Plate',
      gvw: '10,700 kg',
      payload: 'Lifting Capacity: 4,000 kg Container Payload',
      wheelbase: '2,815 mm / 3,335 mm',
      fuelTank: '90 Litres Diesel',
      fuelType: 'Diesel',
      brakes: 'Full Air Dual Circuit with ABS',
      steering: 'Integral Hydraulic Power Steering',
      suspension: 'Semi-Elliptical Heavy Springs with double helper',
      tyres: '8.25 R 20 - 16 PR',
      gradeability: '26%',
      topSpeed: '75 km/h'
    },
    overview: 'The Dpr-8 Dumper Placer is a core asset of urban waste logistics under the Swachh Bharat mission. Its dual hydraulic arms effortlessly lift, transport, and tip municipal containers at dumping sites without requiring workers to handle waste manually.'
  },
  {
    id: 'troop-carrier-4x4',
    name: 'TroopCarrier 4x4 / 4x2',
    series: 'Defense & Police Series',
    tagline: 'Tactical personnel carrier for armed forces, paramilitary & police battalions',
    category: 'special',
    subCategory: 'defense_utility',
    subCategoryLabel: 'Tactical Defense & Security Vehicle',
    startingPrice: '₹ 21.50 Lakh*',
    gvw: '7,200 kg',
    power: '102 HP @ 2600 rpm',
    seatingOrPayload: 'Seating: 20-24 Armed Personnel',
    fuelType: 'Diesel',
    applications: ['Police Quick Reaction Teams (QRT)', 'Paramilitary Patrols (CRPF/BSF/CISF)', 'Riot Control & Law Enforcement', 'Disaster Evacuation & Flood Relief'],
    image: '/assets/raozmotors/special_troop_carrier.jpg',
    highlights: [
      'Available with all-wheel 4x4 drivetrain and high/low transfer case',
      'Heavy-duty waterproof canvas canopy with drop-side wooden/steel benches',
      'Rifle racks, under-seat ammo storage lockers & dual pintle tow hooks',
      'High ground clearance (240 mm) & 600 mm water wading capability'
    ],
    specs: {
      engine: 'SLT6 Military-Spec BS6 Turbo Diesel with high-flow snorkel air intake',
      maxPower: '102 HP @ 2600 rpm',
      maxTorque: '315 Nm @ 1400 - 1600 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 OBD-2 Compliant',
      transmission: '5-Speed Manual with 2-Speed 4x4 Transfer Case',
      clutch: '280 mm Heavy Duty Diaphragm',
      gvw: '7,200 kg',
      seatingCapacity: '22+D (Facing longitudinal bench seats)',
      wheelbase: '3,335 mm',
      fuelTank: '120 Litres with dual jerry can brackets',
      fuelType: 'Diesel',
      brakes: 'Hydraulic Vacuum Assisted Dual Circuit with ABS and Brake Guard',
      steering: 'Heavy-Duty Power Steering',
      suspension: 'Semi-Elliptical Heavy Multi-Leaf Springs with Military Rebound Dampers',
      tyres: '8.25 R 16 Cross-Country Sand/Mud Grip',
      gradeability: '35%',
      topSpeed: '80 km/h'
    },
    overview: 'Built for high durability under harsh field conditions, the TroopCarrier 4x4 has served state police forces and central paramilitary units for over two decades. Its rugged frame and simplified maintenance ensure mission readiness anywhere in the country.'
  },
  {
    id: 'highway-recovery-tow-van',
    name: 'Highway Recovery & Rapid Tow Van',
    series: 'Road Assistance & Recovery',
    tagline: 'Hydraulic underlift towing vehicle with power recovery winch for highway assistance',
    category: 'special',
    subCategory: 'defense_utility',
    subCategoryLabel: 'Highway Rescue & Towing Van',
    startingPrice: '₹ 22.40 Lakh*',
    gvw: '10,700 kg',
    power: '115 HP @ 2400 rpm',
    seatingOrPayload: 'Towing Capacity: Up to 12 Tonnes',
    fuelType: 'Diesel',
    applications: ['National Highway Authority (NHAI) Toll Corridors', 'Traffic Police Vehicle Impound Operations', 'Commercial Fleet Breakdown Assistance', 'Accident Scene Clearance'],
    image: '/assets/raozmotors/special_recovery_tow.jpg',
    highlights: [
      'Heavy hydraulic wheel-lift / underlift arm with 4,500 kg lift capacity',
      '10-Tonne hydraulic power winch with 30-meter high-tensile steel cable',
      'Full LED high-visibility amber warning lightbar & rear work floodlights',
      'Onboard heavy-duty air hose reel and 24V jump-start auxiliary socket'
    ],
    specs: {
      engine: 'SLT6 Turbo Diesel BS6 Phase 2 with high cooling capacity',
      maxPower: '115 HP @ 2400 rpm',
      maxTorque: '400 Nm @ 1300 - 1700 rpm',
      displacement: '3455 cc',
      emissionNorms: 'BS6 Phase 2',
      transmission: '5-Speed Manual with Auxiliary Hydraulic PTO',
      clutch: '310 mm Ceramic Heavy Plate',
      gvw: '10,700 kg',
      payload: 'Towing Capacity: 12,000 kg Gross Combination Weight',
      wheelbase: '3,335 mm',
      fuelTank: '120 Litres Diesel Tank',
      fuelType: 'Diesel',
      brakes: 'Full Air S-Cam with ABS',
      steering: 'Hydraulic Power Steering with Extra Cooling Core',
      suspension: 'Reinforced Multi-Leaf Heavy Spring',
      tyres: '8.25 R 20 - 16 PR',
      gradeability: '28%',
      topSpeed: '80 km/h'
    },
    overview: 'The Highway Recovery Tow Van keeps arterial expressways moving by rapidly clearing immobilized trucks, buses, and private cars. With remote-controlled hydraulic underlift and dual stabilizing spades, it recovers broken-down vehicles without causing road blockages.'
  }
];

export const VEHICLE_CATEGORIES_METADATA = [
  {
    id: 'trucks',
    title: 'Commercial Trucks',
    subtitle: 'From 5.2T light delivery to 12T heavy intermediate haulage',
    count: ALL_COMMERCIAL_VEHICLES.filter(v => v.category === 'trucks').length,
    description: 'Engineered for maximum fuel efficiency, robust payload resilience, and low operational expenditure across Indian city corridors and national highways.',
    icon: 'Truck'
  },
  {
    id: 'buses',
    title: 'Passenger Buses & Coaches',
    subtitle: 'School buses, corporate staff transit and luxury intercity coaches',
    count: ALL_COMMERCIAL_VEHICLES.filter(v => v.category === 'buses').length,
    description: 'Trusted by over 4,500 institutions and tour operators nationwide. Built with stringent AIS 052 & AIS 063 safety codes and plush commuter comfort.',
    icon: 'Bus'
  },
  {
    id: 'special',
    title: 'Special Application Vehicles',
    subtitle: 'LifeLine ambulances, municipal utility, water tankers and defense carriers',
    count: ALL_COMMERCIAL_VEHICLES.filter(v => v.category === 'special').length,
    description: 'Factory-customized commercial chassis for healthcare, civic sanitation, fire rescue, cash logistics, and tactical defense mobility.',
    icon: 'ShieldCheck'
  }
];
